# Generated by Django 2.1.5 on 2021-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('mail', models.EmailField(max_length=50, null=True)),
                ('sub', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
